# Docker Compose file Reference (https://docs.docker.com/compose/compose-file/)

version: '3.3'

services:
  app-server:
    container_name: polls-app-server-prod
    image: 10.115.8.91:5000/polls-app-server-prod
    ports:
      - "8981:8080"
    restart: always
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://polls-app-db-prod:3306/polls?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
      SPRING_DATASOURCE_USERNAME: callicoder
      SPRING_DATASOURCE_PASSWORD: callicoder
    networks:
      - polls-backend-prod
      - polls-frontend-prod

  app-client:
    container_name: polls-app-client-prod
    image: 10.115.8.91:5000/polls-app-client-prod
    ports:
      - "9091:80"
    restart: always
    depends_on:
      - app-server
    networks:
      - polls-frontend-prod

  db:
    image: mysql:5.7
    container_name: polls-app-db-prod
    ports:
      - "33071:3306"
    restart: always
    environment:
      MYSQL_DATABASE: polls
      MYSQL_USER: callicoder
      MYSQL_PASSWORD: callicoder
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - db-data-prod:/var/lib/mysql
    networks:
      - polls-backend-prod

volumes:
  db-data-prod:

networks:
  polls-backend-prod:
  polls-frontend-prod:
